title: Rill Writes
#author: Rill
  # email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: These are my journal entries. They may be useful to you.  
# Build settings

theme: minima

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#    - jekyll-paginate

# Theme-specific settings

#minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

markdown: kramdown
permalink: /:title/

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      isPost: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      isPost: false
      layout: default

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
posts_limit: 5
paginate: 5
per_page: 5

paginate_path: '/page:num/'

# jekyll archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


